---
- name: 3. Install Monitoring (Prometheus & Grafana)
  hosts: all
  become: yes

  tasks:
    - name: Add Prometheus community Helm repo
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
      become: yes
      become_user: ubuntu # Працюємо від користувача, щоб Helm бачив конфіги Kubernetes

    - name: Install Kube-Prometheus-Stack
      shell: |
        helm install monitoring prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace
      become: yes
      become_user: ubuntu
      args:
        # Не запускати, якщо вже встановлено
        executable: /bin/bash
      register: helm_result
      failed_when: 
        - helm_result.rc != 0 
        - '"already exists" not in helm_result.stderr'

    - name: Wait for Prometheus pods to be ready
      shell: kubectl wait --for=condition=Ready pods --all -n monitoring --timeout=300s
      become: yes
      become_user: ubuntu