name: "Ansible CI/CD (Task 2)"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'task2/**' 
  workflow_dispatch: 

jobs:
  ansible:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (щоб завантажити стан)
        working-directory: ./terraform
        run: terraform init

      - name: Get VM IP
        id: get_ip
        working-directory: ./terraform
        run: |
          VM_IP=$(terraform output -raw vm_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV


      - name: Install Ansible
        run: sudo apt update && sudo apt install ansible -y

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          # Беремо справжній приватний ключ з ваших секретів
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Вимикаємо питання "Are you sure you want to continue connecting?"
          echo "StrictHostKeyChecking no" >> ~/.ssh/config


      - name: Run Ansible Playbook
        working-directory: ./task2
        run: |
          ansible-playbook -i "${{ env.VM_IP }}," -u ubuntu --private-key ~/.ssh/id_rsa playbook.yml