name: "Ansible Software Deployment(Task 2)"

on:
  workflow_run:
    workflows: ["Terraform CI/CD"] 
    types: [completed]
  workflow_dispatch: 

jobs:
  ansible:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform & Get IP
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          cd terraform
          terraform init
          VM_IP=$(terraform output -raw vm_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOF > ~/.ssh/config
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            IdentitiesOnly yes
            IdentityFile ~/.ssh/id_rsa
            PubkeyAcceptedAlgorithms +ssh-rsa
            HostkeyAlgorithms +ssh-rsa
          EOF

      - name: Ansible Pre-install Check
        run: |
          # ПЕРЕВІРТЕ ШЛЯХ ДО ПЛЕЙБУКА (task2 чи ansible?)
          ansible-playbook task2/playbook.yml \
            -i "${{ env.VM_IP }}," \
            -u ubuntu \
            --check --diff

      - name: Ansible Real Install
        run: |
          ansible-playbook task2/playbook.yml \
            -i "${{ env.VM_IP }}," \
            -u ubuntu