name: "Task 3: App Build & Deploy"

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'Введіть IP-адресу ВМ (holub-node-new)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout external app (develop branch)
        uses: actions/checkout@v4
        with:
          repository: 'YulianSalo/devops-exam-pt2'
          ref: 'develop'

      - name: Build and push Dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/exam-app:develop

      - name: Checkout external app (tag 1.0.0)
        uses: actions/checkout@v4
        with:
          repository: 'YulianSalo/devops-exam-pt2'
          ref: '1.0.0'

      - name: Build and push Release image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/exam-app:1.0.0

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout YOUR code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.vm_ip }} >> ~/.ssh/known_hosts

      - name: Copy manifest to target VM
        run: |
          scp -i ~/.ssh/id_rsa task3/app-manifest.yaml ubuntu@${{ github.event.inputs.vm_ip }}:/home/ubuntu/app-manifest.yaml

      - name: Deploy and Port-Forward
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.vm_ip }} << 'EOF'
            pkill -f "port-forward.*8002" || true
            pkill -f "port-forward.*8003" || true
            

            sed -e "s|\${ENV_NAME}|dev|g" \
                -e "s|\${IMAGE_TAG}|develop|g" \
                -e "s|\${DOCKER_USER}|${{ secrets.DOCKERHUB_USERNAME }}|g" \
                app-manifest.yaml > dev-deploy.yaml
            
            kubectl apply -f dev-deploy.yaml --dry-run=client
            kubectl apply -f dev-deploy.yaml
            
            sleep 15
            
            nohup kubectl port-forward svc/devops-app-svc 8002:8000 -n dev --address 0.0.0.0 > /dev/null 2>&1 &


            sed -e "s|\${ENV_NAME}|release|g" \
                -e "s|\${IMAGE_TAG}|1.0.0|g" \
                -e "s|\${DOCKER_USER}|${{ secrets.DOCKERHUB_USERNAME }}|g" \
                app-manifest.yaml > release-deploy.yaml
            
            kubectl apply -f release-deploy.yaml --dry-run=client
            kubectl apply -f release-deploy.yaml
            
            sleep 15
            
            nohup kubectl port-forward svc/devops-app-svc 8003:8000 -n release --address 0.0.0.0 > /dev/null 2>&1 &
            
            echo "Успішно розгорнуто!"
          EOF